language: generic
if: tag IS blank
services:
  - docker
before_script:
  - DOCKER_IMAGE=$DOCKER_USERNAME/$APP:$(git describe --always --abbrev --tags --long)
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t $DOCKER_IMAGE .
script:
  - docker run -d $DOCKER_IMAGE
after_success:
  - docker push $DOCKER_IMAGE
before_deploy:
  - echo $HOST1_KNOWN >> ~/.ssh/known_hosts
  - echo $HOST2_KNOWN >> ~/.ssh/known_hosts
  - echo $HOST_DEV_KNOWN >> ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in .travis/deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
  - eval $(ssh-agent -s)
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
deploy:
  - provider: script
    script: ./.travis/deploy.sh production $HOST1 $HOST1_USER $HOST1_PASSWORD $DOCKER_IMAGE
    on:
      branch: master
  - provider: script
    script: ./.travis/deploy.sh production $HOST2 $HOST2_USER $HOST2_PASSWORD $DOCKER_IMAGE
    on:
      branch: master
  - provider: script
    script: ./.travis/deploy.sh development $HOST_DEV $HOST_DEV_USER $HOST_DEV_PASSWORD $DOCKER_IMAGE
    on:
      branch: develop
notifications:
  slack:
    secure: "dyU0HA0n6T+yVUyZto305Rf6QRrLTMy9njN+fwjnvIi+XkNFVR9VDvxcLMDiCc2dIl4UrVPMNOt+z/pNLzd7ZeI4s6RQ3fqHmjsHlKtLEnesaZCt4j8tbGubBOE4n/u6zoyRKa9gxj4YfbWPAWVh0+XpJXYv2g9HpnI95MyQO7iVJdGS/58Tmd7UnOIaYI/L/mUGZyd4PlwEfTSTPYvV1OrOhdUWe6I+xXdWGp0rBnMbBzOzpOeoJGxTNbQ9Ly+r6efhO27859/kZIo3l23ya8N+wGlD27ZizFB51iwNLqVGOdH5RThDRojgzkhp/TxkFRm2K2v10GPveJrKhVf5KbCHYmLuVGen+ZjpnwxsxmvFG/Sl+HHlANhIVjQhOvagk5gMoimhOVQOQvv5Wq53f4GrGiD2bfF2mUuPoaSBYaN1yqbogaTZKhgnCjbv+hnscprSRWamMPOKhkJWx3kSz/P52c21M0OQIn8bHS2539ygbIo3+C9WivYYiPFQnWXRK2vYw8nWEJcaZYaJWjEKflxmG+fqFz50i/028i4th/p/E3dn4mkkQz2/Edj3tbzMLDELyL6ggX03q0wunqPxQujzmwn4QaBvcz9IHqYExeA3PG3gDGXWd9JQMfVwzWgcaRVo3HR21d15sX33lVDH6RurtIBlA7RylMxQlcxR5AE="
    on_pull_requests: false
