language: generic
if: tag IS blank
services:
  - docker
before_script:
  - DOCKER_IMAGE=$DOCKER_USERNAME/$APP:$(git describe --always --abbrev --tags --long)
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t $DOCKER_IMAGE .
script:
  - docker run -d $DOCKER_IMAGE
after_success:
  - docker push $DOCKER_IMAGE
before_deploy:
  - echo $HOST1_KNOWN >> ~/.ssh/known_hosts
  - echo $HOST2_KNOWN >> ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in .travis/deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
  - eval $(ssh-agent -s)
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
deploy:
  - provider: script
    script: ./.travis/deploy.sh $HOST1 $HOST1_USER $HOST1_PASSWORD $DOCKER_IMAGE
    on:
      branch: master
  - provider: script
    script: ./.travis/deploy.sh $HOST2 $HOST2_USER $HOST2_PASSWORD $DOCKER_IMAGE
    on:
      branch: master
notifications:
  slack:
    secure: "n1TaOGAWbuFgcoE8zDyXq7zrUY0muSOMTs4yXueg+x2ZxshgEZhCrD9N8+qCe74Wu6V2hXLSf9BE2CqZ85o5da5rqYaXeZ96S5JF8ROdsMQqLkRlz/9GJVrFN2F90sS7n7amlWiW44P4pGacNMOntOoaLrqAm8Z57E7oUAo+TLOtSBX6kJaMaFSCXnaenMcvP+ZDpUf67+6H63USYsdKZq3DMav5Lhe6BepEhlhYvGamGmICcaEkRcvQ41HcHkkzsk9ICch234N0+BL7dmgjcoJz0Dih/BIOJkWyp8nUXAFGfehjldRl+X7ihr2Ah35fpsx/aLigzpL94ekuPdELZ/d7ijJSGB3FmvWukQlH0srV/udLvJOTEQkv6syL0eDb6Tdup86fK60Hc+oCHUm3TGQ8YAFZd/pQReobtanKueZQXeRzmp2rPWckVY6ratyga+fgMw8TUlsSovWudGqKYuhRvzzt/Sq5RaMcEyDoOzNf7QeFw0SRkqaPtoLJVeCPgb69I10oggSNh9wBmmHcDPR3K616xwHrrrHJZwGVZr71RvLLMPJWkWPtSHVuscm2Aj3Gi+/aIVmKJZx2+owbwmi9oqhx3ptmnMd7qhOJOEmh/NpXf+97gjaCoLJBTiDTCofEB35qjo8QuacfMQo6LOS9doVC/udOTop0JAf75Ng="
    on_pull_requests: false
